var ChessAI=function(a){this.board=a;this.pieces=a.get("pieces");this.array=a.get("board");this.score={p2:10,r2:70,n2:50,b2:80,q2:250,k2:900,p1:10,r1:70,n1:50,b1:80,q1:250,k1:900}};
ChessAI.prototype.move_piece=function(){for(var a=[],d=[],b=this.pieces.getLength(),c=this.pieces.getChildren(),k=0;k<b;k++){var g=c[k];if(1===g.type){var l=this.check_thread(g.pos);0<l&&d.push({x:g.pos.x,y:g.pos.y,score:l});var e=this.board.get_moves(g.pos);l=e.length;if(0<l)for(var h=0;h<l;h++)e[h].ori=g.pos,a.push(e[h])}}e=this.minimax(a);this.shuffle(e);l=e.length;a=-1E3;for(b=0;b<l;b++)if(e[b].score>a){a=e[b].score;var m=e[b]}e=d.length;l=-999;if(0<e)for(a=0;a<e;a++)if(d[a].score>l){l=d[a].score;
var f=d[a]}d=!1;if(l>m.score){d=!0;a=-999;e=this.board.get_moves(f);b=[];l=e.length;for(c=0;c<l;c++)e[c].ori={x:f.x,y:f.y},b.push(e[c]);e=this.minimax(b);l=e.length;if(0<l)for(f=0;f<l;f++){if(e[f].score>a){a=e[f].score;var n=e[f]}}else"q1"===this.array[f.y][f.x]&&(f=this.find_backup(1,f))&&(n=f)}if(d&&n){if("k1"===this.array[n.ori.y][n.ori.x]&&(f=this.find_backup(1,n.ori))&&(n=f),n)return n}else return m};ChessAI.prototype.shuffle=function(a){a.sort(function(){return Math.random()-.5})};
ChessAI.prototype.minimax=function(a,d){for(var b=[],c=a.length,k=0;k<c;k++){var g=a[k];g.score=this.get_score(g);g.score=this.depth_check(g);b.push(g)}return b};
ChessAI.prototype.depth_check=function(a,d){var b=JSON.parse(JSON.stringify(this.array));b[a.y][a.x]=a.key;b[a.ori.y][a.ori.x]=0;return 0<this.board.check(1,a,b).length?"p1"===this.array[a.ori.y][a.ori.x]||"p2"===this.array[a.ori.y][a.ori.x]?0<this.board.check(2,a,b).length?a.score:-10:a.score+-1*this.score[this.array[a.ori.y][a.ori.x]]:a.score};
ChessAI.prototype.check_thread=function(a){var d=this.board.check(1,a),b=-999;if(0<d.length){var c=this.score[this.array[a.y][a.x]];c*=-1;for(var k=0;k<d.length;k++)this.score[this.array[d[k].y][d[k].x]]>b&&(b=this.score[this.array[d[k].y][d[k].x]])}else c=0;0<b&&0<this.board.check(2,a).length&&(c+=b);return-1*c};ChessAI.prototype.get_score=function(a){return 0===this.array[a.y][a.x]?0:this.score[this.array[a.y][a.x]]};
ChessAI.prototype.clone_array=function(a){for(var d=[],b=a.length,c=0;c<b;c++)a[c].splice(),d.push(a[c]);return d};
ChessAI.prototype.find_backup=function(a,d){if(!d){var b=0;a:for(;8>b;b++)for(var c=0;8>c;c++)if(this.array[b][c]==="k"+a)break a}c=[];b=[];for(var k=this.pieces.getLength(),g=this.pieces.getChildren(),l=0;l<k;l++){var e=g[l];if(e.type===a){var h=this.board.get_moves(e.pos),m=h.length;if(0<m)for(var f=0;f<m;f++)h[f].ori=e.pos,h[f].key=this.array[e.pos.y][e.pos.x],c.push(h[f])}}m=c.length;for(k=0;k<m;k++)g=c[k],h=JSON.parse(JSON.stringify(this.array)),h[g.y][g.x]=g.key,h[g.ori.y][g.ori.x]=0,h=this.board.check(a,
!1,h,!0),0===h.length&&b.push(g);if(0<b.length){1===a&&(b=this.minimax(b));c=[];m=[];for(h=0;h<b.length;h++)b[h].eat?c.push(b[h]):m.push(b[h]);if(0<c.length)for(b=-1E3,m=0;m<c.length;m++){if(c[m].score>b){var n=c[m];b=c[m].score}}else for(b=-1E3,c=0;c<m.length;c++)m[c].score>b&&(n=m[c],b=m[c].score);this.rebuild_board();return n}this.rebuild_board();return!1};
ChessAI.prototype.rebuild_board=function(){for(var a=0;8>a;a++)for(var d=0;8>d;d++)this.array[a][d]=0;a=this.pieces.getLength();d=this.pieces.getChildren();for(var b=0;b<a;b++){var c=d[b];this.array[c.pos.y][c.pos.x]=c.key}};